### ISSUE TITLE
Explore adding Pod affinity to make it more reliable

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/endpoint-copier-operator#26]
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

Currently when e-c-o is deployed, there are two replicas of the pod:

```
vm2:~ # kubectl get pods -A -o wide | grep -i endpoint
endpoint-copier-operator          endpoint-copier-operator-7bf97b9d45-ml4mf              1/1     Running     0               20h   10.42.0.100       vm1    <none>           <none>
endpoint-copier-operator          endpoint-copier-operator-7bf97b9d45-zlcsk              1/1     Running     0               20h   10.42.0.194       vm1    <none>           <none>
```

But they can land on the same host if the deployment is triggered when a single node is up (which is the case on SUSE Edge deployments).

If that node dies, e-c-o doesn't update the kubernetes-vip endpoints:

```
vm2:~ # kubectl get nodes
NAME   STATUS     ROLES                       AGE   VERSION
vm1    NotReady   control-plane,etcd,master   20h   v1.31.3+rke2r1
vm2    Ready      control-plane,etcd,master   14m   v1.31.3+rke2r1
vm3    Ready      control-plane,etcd,master   20h   v1.31.3+rke2r1
vm2:~ # kubectl get svc
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                         AGE
kubernetes       ClusterIP      10.43.0.1      <none>           443/TCP                         20h
kubernetes-vip   LoadBalancer   10.43.254.27   192.168.122.10   9345:31445/TCP,6443:30451/TCP   20h
vm2:~ # kubectl get endpoints kubernetes
NAME         ENDPOINTS                                   AGE
kubernetes   192.168.122.252:6443,192.168.122.253:6443   20h
vm2:~ # kubectl get endpoints kubernetes-vip
NAME             ENDPOINTS                                                                    AGE
kubernetes-vip   192.168.122.251:9345,192.168.122.252:9345,192.168.122.253:9345 + 3 more...   20h
```

For example, the cilium operator has this:

```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                io.cilium/app: operator
            topologyKey: kubernetes.io/hostname
```
